### ISSUE TITLE
Overall_reweight and Batch_reweight are not running!!!

### ISSUE THREAD

**Issue by Mah-Zam** [YuWVandy/G2GNN#1]
Hello Dear, 
Thank you for sharing your research paper source code here. I think code is only running with "reweight" instead. Otherwise we will get below error:

G2GNN/learn.py", line 192, in train
    loss.backward()
UnboundLocalError: local variable 'loss' referenced before assignment

Please correct me if I am wrong.

Thank you so much.

**Comment by yuwvandy** [comment]
Hi Mah,
 Thank you for your interesting in our work and code. We have updated our code heavily recently and made changes as follows:
 (1) provide the implementation of both reweight and batch-reweight
 (2) wrap the search of the nearest neighboring graphs within the dataprocess module to allow parallel sampling
 (3) Instead of using the original scatter that is non-deterministic to pool the node representation to the graph representation, we use Segment CSR to implement, allowing the deterministic results.
 
 Please download the most recent codes and run the bash_{dataset}.sh files. And let me know if you have any further issue from there!

**Comment by Mah-Zam** [comment]
Sure. May I know how can I contact you? I have multiple advanced research projects and would like to write some papers. Of course, if you are interested. The results are available. About the Grakel package which you have used in your project, I need to change their libraries to use our dataset while I have changed and generated my script using torch_geometric for new datasets. Do you know how we can do that? Thanks again

**Comment by yuwvandy** [comment]
> Sure. May I know how can I contact you? I have multiple advanced research projects and would like to write some papers. Of course, if you are interested. The results are available. About the Grakel package which you have used in your project, I need to change their libraries to use our dataset while I have changed and generated my script using torch_geometric for new datasets. Do you know how we can do that? Thanks again

It is interesting that you are trying to use some of our techniques developed here. My email is yu.wang.1@vanderbilt.edu. Feel free to drop me an email and if you have Wechat, you can also send me your Wechat via email so that we can chat there if it is more convenient for you. 

I think this post would provide some insights on how to calculate kernel similarity for customized datasets. https://github.com/ysig/GraKeL/issues/59. However, if the number of graphs/ the size of every single graph is too large, we might need some advanced techniques to deal with the complexity there. We can discuss this furthermore via email.

**Comment by Mah-Zam** [comment]
Hello Yu, I would like to meet you in Wechat. I will wait your response, I sent you an email. Thanks
